#!/bin/sh

# adhoc weimarnetz 2432 10.63.9.1
# adhoc white 2412 192.168.11.235  <--- static IP channel 1
# OR
# adhoc white 2412 dhcp 192.168.5.1 <--- dhcp channel 1 with default gateway of 192.168.5.1 
# OR
# adhoc white  <-- defaults to dhcp and channel 6 with gateway 192.168.5.1

set -x

get_wifidev()
{
	set -- $( tail -n1 '/proc/net/wireless' )
	echo ${1%:*}	# wlan0: -> wlan0
}

wifidevice="$( get_wifidev )"
BSSID='02:ca:ff:ee:ba:be'		# hardcoded IBSS-cell-ID / freifunk-default
DAEMON=					# babel / batman-adv / batman / bmx / o11s / olsr

SSID="$1"
[ -z "$SSID" ] && {
	echo -e "\nSSID not specified"
	echo "Exiting..."

	exit 1	
}

freq="$2"
[ -z "$freq" ] && {
	freq=2437
}

dhcp=0
[ "$3" = 'dhcp' ] && {
	dhcp=1
}

[ -z "$3" ] && {
	dhcp=1
}

[ "$DAEMON" = "batman-adv" ] && {
	gateway="$4"
	[ -z "$gateway" ] && {
		gateway=192.168.5.1
	}
}

echo -ne "\nPreparing devices.... \n" 
[ "$DAEMON" = "batman-adv" ] && rmmod batman-adv 2>/dev/null
killall wpa_supplicant 2>/dev/null
ifconfig "$wifidevice" down 2>/dev/null
[ "$DAEMON" = "batman-adv" ] && ifconfig "bat0" 0.0.0.0 2>/dev/null
ifdown -a


echo -ne "\nSetting up interface '$wifidevice' \n"


ifconfig "$wifidevice" up 2>/dev/null
iw "$wifidevice" set type ibss
iw "$wifidevice" ibss join "$SSID" "$freq"
iwconfig "$wifidevice" ap "$BSSID"

if [ "$dhcp" -eq 1 ]; then
	[ "$DAEMON" = "batman-adv" ] && route add default gw "$gateway" 2>/dev/null

	udhcpc -i "$wifidevice" -q -n || {
		echo -e "\nUnable to obtain ip address"
		echo "Exiting..."

		ifconfig "$wifidevice" down 2>/dev/null
		ifdown -a

		exit 1		
	}
	
else
	ifconfig "$wifidevice" "$3"  2>/dev/null
fi

echo -ne "\nConnected to $SSID \n"

exit 0
