#!/bin/sh

# adhoc white 2412 192.168.11.235  <--- static IP channel 1
# OR
# adhoc white 2412 dhcp 192.168.5.1 <--- dhcp channel 1 with default gateway of 192.168.5.1 
# OR
# adhoc white  <-- defaults to dhcp and channel 6 with gateway 192.168.5.1

get_wifidev()
{
	set -- $( tail -n1 '/proc/net/wireless' )
	echo ${1%:*}	# wlan0: -> wlan0
}

wifidevice="$( get_wifidev )"

SSID=$1
if [ "$SSID" == "" ]; then
	echo -e "\nSSID not specified"
	echo "Exiting..."

	exit 1	
fi

freq=$2
if [ "$freq" == "" ]; then
	freq=2437
fi

dhcp=0
if [ "$3" == "dhcp" ]; then
	dhcp=1
fi

if [ "$3" == "" ]; then
	dhcp=1
fi

gateway=$4
if [ "$gateway" == "" ]; then
	gateway=192.168.5.1
fi

echo -ne "\nPreparing devices.... \n" 
rmmod batman-adv 2>/dev/null
killall wpa_supplicant 2>/dev/null
ifconfig $wifidevice down 2>/dev/null
ifconfig bat0 0.0.0.0 2>/dev/null
ifdown -a


echo -ne "\nSetting up interface $wifidevice \n"


ifconfig $wifidevice up 2>/dev/null
iw $wifidevice set type ibss
iw $wifidevice ibss join $SSID $freq


if [ $dhcp -eq 1 ]; then

	route add default gw $gateway 2>/dev/null

	udhcpc -i "$wifidevice" -q -n
	if [ $? -ne 0 ]; then
		echo -e "\nUnable to obtain ip address"
		echo "Exiting..."

		ifconfig $wifidevice down 2>/dev/null
		ifdown -a

		exit 1		
	fi
	
else
	ifconfig $wifidevice $3  2>/dev/null
fi

echo -ne "\nConnected to $SSID \n"

exit 0
