#!/bin/sh

killall chvt 2>/dev/null

currPid=`cat /tmp/run/gmenu.pid 2>/dev/null`

if [ $? -eq 0 ]; then
		
	/usr/local/sbin/killtree.sh $currPid
	rm /tmp/run/gmenu.pid 2>/dev/null
    rm /tmp/vt/gmenu 2>/dev/null
else

	max_tty=`cat /tmp/vt/gmenu2x` 2>/dev/null
	if [ -z "$max_tty" ]; then
		pid=`pidof gmenu2x.bin`

       while [ -z "$pid" ]; do
      		#something has gone wrong and is blocking gmenu2x from
      		#starting, hopefully the following line(s) will get it going again

            killall -9 chvt 2>/dev/null
            killall -9 gmenu2x 2>/dev/null
#           killall -9 z2-shell
			sleep 1

            pid=`pidof gmenu2x.bin`
                    
        done


		max_tty=0
	
		cd /proc/$pid/fd

		for item in *
		do
			if [ $(($item)) -gt 2 ]; then
				local tty=`readlink $item |grep '/dev/tty'|grep -Eo -e "[0-9]|[0-9][0-9]"`
				if [ $tty ] && [ $tty -gt $max_tty ]; then
					max_tty=$tty
				fi
			fi
		done
 	

		if [ $max_tty -gt 0 ]; then
			echo $max_tty >/tmp/vt/gmenu2x
		 	chvt $max_tty 
		else
			rm /tmp/vt/gmenu2x 2>/dev/null
		fi


	else
 		chvt $max_tty
	fi

fi

